# Generated by Django 5.2.7 on 2025-11-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_question_lifespan_days_alter_question_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description_short',
            field=models.TextField(blank=True, help_text='кратенько кратко', max_length=300, null=True, verbose_name='краткое описание'),
        ),
    ]
